// Generates inline pixel-art SVG frames for the DSKIN pets.
// mouse: idle (bob), blink, walk A/B (stepping legs).
// whale: idle, blink, walk A/B (tail-fin wiggle).
// Run: node scripts/gen-mascots.mjs
const MOUSE_HEAD = [
  '..KK........KK.......',
  '.KYYK......KYYK......',
  '.KYYYK....KYYYK......',
  'KYYYYK....KYYYYK.....',
  'KYYYYYYYYYYYYYYK.....',
  'KYYYYYYYYYYYYYYK.....',
  'KYYEYYYYYYYEYYK......',
  'KYYEwYYYYYYEwYK......',
  'KYYEYYYYYYYEYYK......',
  'KYYCYYYYYYCYYK.S.....',
  'KYYCCYYYYYCCYYK.S....',
  'KYYYYYYYYYYYYYK..S...',
  '.KKKKKKKKKKKKKK..SS..',
]
const MOUSE_BLINK = MOUSE_HEAD.map((row, i) => {
  if (i === 6) return 'KYYKYYYYYYYKYK......'
  if (i === 7) return 'KYYKYYYYYYYKYK......'
  return row
})
const MOUSE_WALK_A = [...MOUSE_HEAD, '..KKKK......KKKK.....', '..KK..........KK.....']
const MOUSE_WALK_B = [...MOUSE_HEAD, '..KK..........KK.....', '..KKKK......KKKK.....']

const WHALE_IDLE = [
  '.....ss........',
  '.....ss........',
  '....ssss.......',
  '....KKKK.......',
  '..KKWWWWKK.....',
  '.KWWWWWWWWK....',
  'KWWWWWWWWWWK...',
  'KWEwBBBBKKWWK..',
  'KWWKBBBBKKWWK..',
  'KWWWWWWWWWWWK..',
  '.KWWWWWWWWWK...',
  '..KWWWWWWWK....',
  '..KKK...KKK....',
  '..K......K.....',
]
const WHALE_BLINK = WHALE_IDLE.map((row, i) => (i === 7 ? 'KWWKBBBBKKWWK..' : row))
const WHALE_WALK_A = WHALE_IDLE.map((row, i) => (i === 12 ? '..KKK....KK....' : row))
const WHALE_WALK_B = WHALE_IDLE.map((row, i) => (i === 12 ? '..KK...KKKK....' : row))

const PALETTE = {
  K: '#2e3a59',   // ink outline
  Y: '#ffd23f',   // mouse body
  E: '#2e3a59',   // eyes
  w: '#ffffff',   // eye glint
  C: '#ff8c69',   // cheeks
  S: '#ffd23f',   // tail lightning
  W: '#4a90d9',   // whale body
  B: '#eef4ff',   // whale belly
  s: '#9fd8ff',   // spout
}
function svg(map) {
  const rects = []
  for (let y = 0; y < map.length; y++) {
    for (let x = 0; x < map[y].length; x++) {
      const ch = map[y][x]
      if (ch === '.' || ch === undefined) continue
      rects.push(`<rect x="${x}" y="${y}" width="1" height="1" fill="${PALETTE[ch]}"/>`)
    }
  }
  const width = Math.max(...map.map((r) => r.length))
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${map.length}" shape-rendering="crispEdges" aria-hidden="true">${rects.join('')}</svg>`
}
const out = {
  MOUSE_IDLE: svg(MOUSE_HEAD),
  MOUSE_BLINK: svg(MOUSE_BLINK),
  MOUSE_WALK_A: svg(MOUSE_WALK_A),
  MOUSE_WALK_B: svg(MOUSE_WALK_B),
  WHALE_IDLE: svg(WHALE_IDLE),
  WHALE_BLINK: svg(WHALE_BLINK),
  WHALE_WALK_A: svg(WHALE_WALK_A),
  WHALE_WALK_B: svg(WHALE_WALK_B),
}
const ts = `// GENERATED by scripts/gen-mascots.mjs — do not edit by hand.\n\n` +
  Object.entries(out).map(([k, v]) => `export const ${k} = ${JSON.stringify(v)}`).join('\n\n') + '\n'
console.log(ts)
