// Generates inline pixel-art SVG frames for the DSKIN pet (cartoon mouse).
// Frames: idle (bob), blink, walk A, walk B. Run: node scripts/gen-mascots.mjs
const HEAD = [
  '..KK........KK.......',
  '.KYYK......KYYK......',
  '.KYYYK....KYYYK......',
  'KYYYYK....KYYYYK.....',
  'KYYYYYYYYYYYYYYK.....',
  'KYYYYYYYYYYYYYYK.....',
  'KYYEYYYYYYYEYYK......',
  'KYYEwYYYYYYEwYK......',
  'KYYEYYYYYYYEYYK......',
  'KYYCYYYYYYCYYK.S.....',
  'KYYCCYYYYYCCYYK.S....',
  'KYYYYYYYYYYYYYK..S...',
  '.KKKKKKKKKKKKKK..SS..',
]
const BLINK = HEAD.map((row, i) => {
  if (i === 6) return 'KYYKYYYYYYYKYK......'
  if (i === 7) return 'KYYKYYYYYYYKYK......'
  if (i === 8) return 'KYYEYYYYYYYEYYK......'
  return row
})
const WALK_A = [
  ...HEAD.slice(0, 13),
  '..KKKK......KKKK.....',
  '..KK..........KK.....',
]
const WALK_B = [
  ...HEAD.slice(0, 13),
  '..KK..........KK.....',
  '..KKKK......KKKK.....',
]
const PALETTE = {
  K: '#2e3a59',   // ink outline
  Y: '#ffd23f',   // body
  E: '#2e3a59',   // eyes
  w: '#ffffff',   // eye glint
  C: '#ff8c69',   // cheeks
  S: '#ffd23f',   // tail lightning
}
function svg(map) {
  const rects = []
  for (let y = 0; y < map.length; y++) {
    for (let x = 0; x < map[y].length; x++) {
      const ch = map[y][x]
      if (ch === '.' || ch === undefined) continue
      rects.push(`<rect x="${x}" y="${y}" width="1" height="1" fill="${PALETTE[ch]}"/>`)
    }
  }
  const width = Math.max(...map.map((r) => r.length))
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${map.length}" shape-rendering="crispEdges" aria-hidden="true">${rects.join('')}</svg>`
}
const out = {
  IDLE: svg(HEAD),
  BLINK: svg(BLINK),
  WALK_A: svg(WALK_A),
  WALK_B: svg(WALK_B),
}
const ts = `// GENERATED by scripts/gen-mascots.mjs — do not edit by hand.\n\n` +
  Object.entries(out).map(([k, v]) => `export const ${k} = ${JSON.stringify(v)}`).join('\n\n') + '\n'
console.log(ts)
